---
title: "Ongoing Projects"
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### PINGS-2

The PINGS-2 (Phone-Based Intervention under Nurse Guidance after Stroke) is a multicenter randomized
controlled trial where routine care of patients who had a recent stroke is compared to those who
have nursing support in managing their blood pressure after the stroke.

### Pediatric echocardiogram in Kumasi

This is a review of electrocardiograms done in pediatric patients since 2010. It seeks to bring out
the changing patterns of the common diagnosis and age at diagnosis of the patients.

### SPARCo

The Sickle Pan-African Consortium (SPARCO-II) consists of a hub in East Africa (Tanzania) and
collaborative consortium sites in West Africa (Ghana, Nigeria) and central Africa (Cameroon,
Democratic Republic of Congo) which will expand to form the Sickle Pan-African Network involving 20
sites in 15 countries. This consortium is into research involving every aspect of Sickle Cell
Disease in both children and adults.
